.gitignore, torch_np/tests/numpy_tests/core/test_dtype.py, torch_np/tests/numpy_tests/core/test_getlimits.py, torch_np/tests/numpy_tests/core/test_numerictypes.py, torch_np/tests/numpy_tests/core/test_scalar_ctors.py, torch_np/tests/numpy_tests/core/test_scalar_methods.py, torch_np/tests/numpy_tests/core/test_scalarinherit.py, torch_np/tests/numpy_tests/core/test_scalarmath.py
In the spirit of https://github.com/Quansight-Labs/numpy_pytorch_interop/issues/10#issuecomment-1369591663, vendor scalar and dtype related tests from numpy. Making sure they actually pass will be in the follow-up, gh-12 and gh-14.
=> Numpy tests types and dtypes

torch_np/testing/__init__.py, torch_np/testing/testing.py, torch_np/testing/utils.py
Wanted to bring in numpy tests of dtypes to finish up gh-12, but of course these tests use all sorts of things from `numpy.testing`. So let's port it first. 
The current status:
- previous tests pass
- numpy dtype/scalar tests are not in yet
- had to merge the gh-12 branch because `np.bool_(value)` etc. So no clean separation of concerns, no small PRs just yet, sadly.
- need to carefully decide  what is a _scalar_, cf `isscalar` function, cf https://numpy.org/doc/stable/reference/generated/numpy.isscalar.html
- `testing` module has nice habit of importing stuff from numpy within functions, so anything not exercised by tests is broken. At some point we'll need a CI run without numpy.
=> WIP: port numpy testing

torch_np/__init__.py, torch_np/random.py
Only mimic the old numpy random API.
No guarantees about reproducibility etc beyond those of pytorch.
For the moment, only add a minimal subset to help porting the numpy test suite.
Is on top of gh-22, for clarity.
=> add a minimal `np.random` analog

.pre-commit-config.yaml
For some reason this fixes some problem I was having locally, and it doesn't seem I'm the only one https://github.com/home-assistant/core/issues/86892#issuecomment-1407641288.
<details>
<summary>local error</summary>
```python
An unexpected error has occurred: CalledProcessError: command: ('/home/honno/.cache/pre-commit/reposgg8ow6c/py_env-python3.9/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
Processing /home/honno/.cache/pre-commit/reposgg8ow6c
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'error'
stderr: …
```
=> Bump `isort` pre-commit rev to `5.12.0`

torch_np/random.py
`random.randint(3)` should return an integer, not a float.
=> BUG: random: randint returns integers, not floats

torch_np/tests/numpy_tests/lib/test_nanfunctions.py
Add numpy tests for nanfunctions, verbatim from numpy commit 2aa0bf6973b709724624db8e8a51d8efbdeb5d22 (Jan 2023)
As discussed in https://github.com/Quansight-Labs/numpy_pytorch_interop/issues/10#issuecomment-1369591663, this PR only brings the test file (the only change is imports from numpy -> torch_np).
=> TST: add tests/lib/test_nanfunctions.py from numpy

torch_np/_helpers.py, torch_np/_ndarray.py, torch_np/_wrapper.py, torch_np/tests/test_ufuncs_basic.py
Also restore np.zeros defaulting to float64
=> Fix  __rop__ dunders

torch_np/tests/numpy_tests/core/test_numeric.py, torch_np/tests/numpy_tests/lib/test_function_base.py, torch_np/tests/numpy_tests/lib/test_nanfunctions.py, torch_np/tests/numpy_tests/lib/test_shape_base_.py
datatime, objects, structured dtypes, longdouble
=> TST: trim tests of unsupported numpy features

autogen/numpy_api_dump.py, torch_np/_detail/implementations.py, torch_np/_ndarray.py, torch_np/_wrapper.py, torch_np/tests/numpy_tests/lib/test_shape_base_.py
The main difference with pytorch is that numpy expects `indices_or_sections` as indices into the array to split, while pytorch takes lengths of sections. Also some differences in what exactly happens when the length of the array to split is not equally divisible into sections. And some edge cases for when there are empty sections.
=> WIP: implement {array_, VHD}split

.github/workflows/basic.yml
IIUC, GH hosted runners have two cores (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), so use them.
=> CI: use pytest-xdist with 2 cores on GHA

torch_np/_ndarray.py
Implements [`x.flags`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html), which mostly raises `NotImplementedError()`. Seemed nice if just for porting NumPy's own tests.
=> Basic `ndarray.flags` implementation

.github/workflows/basic.yml
Currently our test CI only runs for `main` changes, so it'd be nice to get it running for any other branches, and when folks open/push-to PRs generally.
=> Run test CI on pushes for any branch and PR activity

torch_np/_dtypes.py, torch_np/_ndarray.py, torch_np/_wrapper.py, torch_np/tests/numpy_tests/core/test_numeric.py, torch_np/tests/numpy_tests/lib/test_shape_base_.py, torch_np/tests/test_xps.py
while at it, un-xfail test_numeric.py::TestTypes.
=> Make ones/zeros/empty/full dtype handling more uniform

torch_np/_decorators.py, torch_np/_detail/_reductions.py, torch_np/_detail/_util.py, torch_np/_detail/implementations.py, torch_np/_dtypes.py, torch_np/_getlimits.py, torch_np/_ndarray.py, torch_np/_wrapper.py, torch_np/tests/numpy_tests/lib/test_type_check.py
Working towards moving actual logic to `_detail`, so that top level modules (currently, _wrappers.py, _ndarray.py) unwrap/normalize their inputs and pass heavy lifting to `_detail`. Details of organization of the `_detail` submodules are TBD, and so are details of unwrapping/normalization or arguments. This PR is to only to make the split as clean as reasonable.
=> make better split between wrappers and torch implementations

autogen/numpy_api_dump.py, torch_np/_detail/implementations.py, torch_np/_ndarray.py, torch_np/_wrapper.py, torch_np/tests/numpy_tests/core/test_numeric.py, torch_np/tests/numpy_tests/lib/test_shape_base_.py, torch_np/tests/test_ndarray_methods.py
This started as an experiment with `torch.scatter_`; that had a limited success, but at least we have sort and argsort which were needed for tests.
=> ENH: {arg}sort, {take, put}along_axis

torch_np/__init__.py, torch_np/_detail/_index_tricks.py, torch_np/_detail/implementations.py, torch_np/_dtypes.py, torch_np/_helpers.py, torch_np/_ndarray.py, torch_np/_wrapper.py, torch_np/testing/__init__.py, torch_np/testing/utils.py, torch_np/tests/numpy_tests/core/test_indexing.py, torch_np/tests/test_helpers.py, torch_np/tests/test_ndarray_methods.py, torch_np/tests/test_xps.py
WIP, no need for review yet. Currently going through [`core/tests/test_indexing.py`](https://github.com/numpy/numpy/blob/main/numpy/core/tests/test_indexing.py), might include (much smaller) test files that also cover indexing.
=> Port indexing tests

torch_np/_ndarray.py, torch_np/tests/numpy_tests/core/test_indexing.py, torch_np/tests/numpy_tests/core/test_numeric.py, torch_np/tests/numpy_tests/lib/test_function_base.py
Implement `f_contguous` flag, also heuristics for `owndata` and `writeable` flags.
=> add ndarrays.flags.f_contiguous

.github/workflows/basic.yml, torch_np/tests/conftest.py
* Skips any test with the `pytest.mark.slow` marker by default like in NumPy
* Introduces `--runslow` option to run these slow tests
* Uses `--runslow` on our test CI
=> `@pytest.mark.slow` and `--runslow` option

autogen/numpy_api_dump.py, torch_np/_detail/_flips.py, torch_np/_detail/_reductions.py, torch_np/_detail/_util.py, torch_np/_detail/implementations.py, torch_np/_ndarray.py, torch_np/_wrapper.py, torch_np/random.py, torch_np/tests/numpy_tests/core/test_multiarray.py, torch_np/tests/numpy_tests/core/test_numeric.py, torch_np/tests/numpy_tests/lib/test_arraysetops.py, torch_np/tests/numpy_tests/lib/test_function_base.py, torch_np/tests/numpy_tests/lib/test_index_tricks.py
Only
are left for a tentative minimum viable functionality set.
=> wrap more functions to complete a minimal viable feature set 

torch_np/_detail/_ufunc_impl.py, torch_np/_detail/implementations.py, torch_np/_funcs.py, torch_np/_ndarray.py, torch_np/_wrapper.py, torch_np/tests/numpy_tests/core/test_multiarray.py
Now that both np.dot and ndarray.dot are there, can remove xfails in tests. Which, in turn, smokes out several problems in arange(..., dtype=complex), so fix them. And while at it, remove xfails of TestArange itself and fix it, too :-)
=> Add ndarray.dot

torch_np/tests/conftest.py
Using `--nonp` will error before any tests are run when NumPy is accessed. I think this is especially useful as we can use it iteratively—
```console
$ cat torch_np/tests/test_foo.py
def test_foo:
assert True
$ pytest torch_np/tests/test_foo.py
```
No error is raised because the tests pytest has collected never import NumPy. Meanwhile 
```console
$ cat torch_np/_uses_numpy.py
import numpy as np
...
np.int8
...
$ cat torch_np/tests/test_bar.py
from torch_np import _uses_numpy
$ pytest torch_np/tests/test_bar.py
...
ERROR torch_np/tests/test_bar.py - RuntimeError: Using --nonp but accessed np.int8
torch_np/tests/test_bar.py:1: in <module>
???
torch_np/_uses_numpy.py:4: in <module>
???
torch_np/tests/conftest.py:20: in __getattribute__
???
E   RuntimeError: Using --nonp but accessed np.int8 …
```
=> Introduce `--nonp` to error when NumPy is accessed

torch_np/tests/conftest.py
@ev-br here's how one could test both NumPy-proper and `torch_np` on the same test. Essentially any test case just needs a parameter `np`, which should be treated as the array module we want to test (i.e. `numpy`, `torch_np`), and we need to ensure we're using that module rather than outside imports.
I reworked some of `test_indexing.py` to demonstrate how this could be utilised. It's a bit finnicky as you have to check `np is {numpy,torch_np}` for some module-specific behaviour, e.g. raised error classes and skips/xfails, and you have to make sure you're using the argument `np` for things like the `{numpy,torch_np}.testing` utils.
Maybe we could support `np` as a magically param but not really bother to rework existing tests with it—instead we use it as-and-when we feel it useful to …
=> Support testing `np` and `tnp` on the same test

torch_np/_decorators.py, torch_np/_dtypes.py, torch_np/_helpers.py, torch_np/_ndarray.py, torch_np/_wrapper.py, torch_np/tests/numpy_tests/core/test_indexing.py, torch_np/tests/numpy_tests/lib/test_shape_base_.py, torch_np/tests/test_ndarray_methods.py
closes gh-47
Base tensor relationship is tracked via pytorch'es `tensor._base` already, so remove  `ndarray.base` attribute.
Checking an wrapper array base becomes then
```
>>> a.get()._base is b.get()
```
instead of numpy's
```
>>> a.base is b
```
This is the second PR in the "stack" based off gh-70.
EDIT : a.get() is gone, so it's `a.tensor._base`  now. 
closes gh-47
=> API: remove ndarray.base

torch_np/_detail/_reductions.py, torch_np/_detail/implementations.py, torch_np/_funcs.py, torch_np/_normalizations.py, torch_np/_wrapper.py, torch_np/tests/numpy_tests/lib/test_function_base.py
This finishes up the move of all work to be done on the torch level in `detail`, and the wrappers are as thin as it gets AFAICS.
=> MAINT: split remaining functions into normalizations and implementations

torch_np/_detail/implementations.py, torch_np/_funcs.py, torch_np/_helpers.py, torch_np/_normalizations.py, torch_np/_wrapper.py, torch_np/random.py
An alternative to gh-83: Dispatch on the type of the return object, wrap tensors into arrays and sequences into sequences of arrays. 
All this allows to inline _helpers.{to_tensors, array_from, tuple_arrays_from}
=> MAINT: automagically wrap return values to ndarrays / lists / tuples

torch_np/__init__.py, torch_np/_funcs.py, torch_np/_ndarray.py, torch_np/linalg.py, torch_np/tests/numpy_tests/linalg/test_linalg.py
Implement linalg mappings. This PR does nearly all of linalg (sans einsum). So far this is not completely consistent on
- the type of exceptions: torch raises RuntimeErrors, sometimes `torch._C._LinAlgError`s; we mostly pass the former through and convert the latter
- zero-size arrays. NumPy handles them, but torch doesn't seem to. So just xfail the corresponding tests.
=> add torch_np.linalg module

torch_np/__init__.py, torch_np/_funcs.py, torch_np/_ndarray.py, torch_np/linalg.py, torch_np/tests/numpy_tests/linalg/test_linalg.py
minimal changes, only to make tests pass collection stage and xfail.
gh-100 implements tnp.linalg and unxfails tests added here.
=> TST: port numpy/linalg/tests/test_linalg.py

torch_np/tests/numpy_tests/linalg/test_linalg.py
A small bump of test tolerance, which shows up _sometimes_ in follow-up PRs.
=> TST: bump test tolerance in TestQR

torch_np/_funcs.py, torch_np/_funcs_impl.py, torch_np/_ndarray.py, torch_np/tests/numpy_tests/core/test_multiarray.py, torch_np/tests/numpy_tests/core/test_numeric.py, torch_np/tests/numpy_tests/lib/test_histograms.py
=> add copyto, resize, histogram

torch_np/_helpers.py, torch_np/_ufuncs.py, torch_np/tests/numpy_tests/core/test_multiarray.py, torch_np/tests/test_ufuncs_basic.py
Mimic numpy: dtype= argument forces the cast of inputs, and out= argument forces the cast (and broadcast) of the result.
This way, `out=` array never plays any role in dispatching. 
This is still somewhat simplified as compared to numpy since we do not have explicit loop types. So rely on pytorch doing the right thing under the hood and see if issues surface in real world testing. 
Closes gh-97.
=> BUG: fix dtype handling in ufuncs

torch_np/_funcs_impl.py, torch_np/_normalizations.py, torch_np/_ufuncs.py, torch_np/tests/test_basic.py
Arguments annotated as NDArray get normalized to their Tensors for further processing by implementer functions.
out= arguments however are special (the original array need to be preserved), and are never seen by implementers, so they keep being ndarrays.
So the annotations and their corresponding normalizations are
- ArrayLike : a generic numpy array_like --- convert to Tensor, pass the Tensor to implementers
- NDArray : ndarray exactly --- check the type to be ndarray, extract its Tensor, pass the Tensor to implenters
- OutArray : ndarray exactly --- check the type to be ndarray, return ndarray, handle it on the `normalizer` level
=> MAINT: normalize NDArray to tensors, add a special-case for out= NDArrays

torch_np/_normalizations.py, torch_np/_ufuncs.py, torch_np/tests/test_basic.py
A minimal fix for a bug in handling of `out=(ndarray, ndarray)`.
=> BUG: fix nout=2 ufuncs

torch_np/_detail/_reductions.py, torch_np/_detail/_util.py, torch_np/_funcs_impl.py, torch_np/_normalizations.py, torch_np/_ufuncs.py, torch_np/tests/test_basic.py
as discussed in https://github.com/Quansight-Labs/numpy_pytorch_interop/pull/112#discussion_r1162861446
This does seem to gain a marginal LOC reduction and some possible readability improvement. Two points:
- I'm {ab,re}using the `NotImplemented` singleton as the annotation. Introducing a new `NotImplementedType` is a bit awkward since `typing.NotImplementedType` is a thing from python 3.10, and we need to cover 3.8+. A simple alternative is to just use `type(NotImplemented)` instead of `NotImplemented`. Don't have a firm opinion, am open to suggestions.
- NumPy uses a weird `_NoValue` sentinel in some cases; we mimicked it by defining an alias `NoValue = None`. In our usage we typically raise NotImplementedError on things with the `NoValue` default. Now that we have a dedicated …
=> MAINT: handle not implemented arguments centrally, via a dedicated annotation

.gitignore, torch_np/_funcs_impl.py, torch_np/tests/numpy_tests/core/test_multiarray.py, torch_np/tests/numpy_tests/core/test_shape_base.py, torch_np/tests/test_basic.py, torch_np/tests/test_function_base.py, torch_np/tests/test_ndarray_methods.py
- Give up trying to imitate the NumPy exceptions altogether
- Remove duplicated round, real imag
- Remove the implementation of nanmean, as it had a number of issues. If we implement masked reducitons, we should probably do them all in one go, reusing the aux functions we used for reductions.
- Minor cosmetic changes
=> Assorted fixes and simplifications

torch_np/_ndarray.py
This PR makes the registration of methods in `ndarray` uniform. It also corrects their `__name__` and `__qualname__` attributes.
While doing this, we fix many r-looking dunder methods that were not correctly implemented see e.g.
https://github.com/Quansight-Labs/numpy_pytorch_interop/pull/2#discussion_r1162547828. We also add the variants of `divmod`, which were missing.
=> Simplify registartion of methods in ndarray

torch_np/__init__.py, torch_np/fft.py, torch_np/tests/numpy_tests/fft/test_helper.py, torch_np/tests/numpy_tests/fft/test_pocketfft.py
Is mostly straightforward, as pytorch API is nearly identical indeed. The main difference seems to be that  `numpy.fft` returns 64-bit transforms for all input dtypes. We now have `set_default_dtype` though, so we probably want fft routines to react to it: 
```
>>> a = np.arange(5, dtype=np.float32)
>>> np.fft.fft(a).dtype == np.complex128            # this is the (numpy) way
True
>>> np.set_default_dtype("pytorch")
>>> np.fft.fft(a).dtype == np.complex64
```
=> add wrappers for np.fft

torch_np/_dtypes.py, torch_np/_funcs_impl.py, torch_np/_ndarray.py, torch_np/testing/utils.py, torch_np/tests/numpy_tests/core/test_multiarray.py, torch_np/tests/test_xps.py
`put()` implementation and my own test. This was tricky but I think it's pretty robust, sans the TODO
Notably in `test_put` I'm testing `tnp.put()` output against NumPy's own `np.put()`, which as you can see is a bit noisy right now due to `tnp.asarray()` not carrying over dtypes (yet? something I'd like to fix as it enables future "comparison testing").
=> `tnp.put()` + testing

torch_np/_funcs_impl.py, torch_np/_normalizations.py, torch_np/_reductions.py, torch_np/linalg.py, torch_np/tests/test_basic.py
- Avoid the repetition of the signature of reductions
- Fix keepdims. With the previous implementation it was not possible to set it as a positional arg.
- Fix some functions that were incorrectly exported in `torch_np`. Added a test for this as well.
- To go with this, I had to move the imports back into `einsum` to avoid having an `from _normalizations import` and a `import _normalizations` right after it, as discussed.
=> Clean-up reductions

torch_np/__init__.py, torch_np/_ndarray.py, torch_np/tests/numpy_tests/core/test_dlpack.py
Just delegate to whatever self.tensor does under the hood.
- vendor the numpy tests suite
- remove datetimes, structured dtypes etc
- had to xfail refcounting related tests --- checked that pytorch does not pass these either.
- had to xfail a test with a non-None dlpack stream --- checked that pytorch does not raise
Also added a small test to check that tnp arrays can be created from / exported to pytorch tensors.
Poking around in ipython, it seems that `np.from_dlpack(torch.Tensor)` creates a readonly array, while the other direction it's a view. Not sure if there's something to do or if we can do anything about it really.
```
In [48]: a = np.arange(3)
In [49]: a
Out[49]: array([0, 1, 2])
In [50]: t = torch.from_dlpack(a)
In [51]: t[0] = 42
In [52]: t
Out[52]: tensor([42,  1,  2])
In …
```
=> Wrap from_dlpack and its dunders

torch_np/_funcs.py, torch_np/_funcs_impl.py, torch_np/tests/numpy_tests/core/test_multiarray.py
Just follow the source, https://github.com/numpy/numpy/blob/maintenance/1.24.x/numpy/core/src/multiarray/convert_datatype.c#L1288
=> implement min_scalar_type

torch_np/random.py, torch_np/tests/test_random.py
Add a global switch to select the random stream origin: pytorch or numpy. If points to NumPy, `tnp.random.uniform` just calls `numpy.random.uniform` etc.
=> ENH: control a random stream to be from either numpy or pytorch

torch_np/_binary_ufuncs_impl.py, torch_np/_dtypes.py, torch_np/_dtypes_impl.py, torch_np/_funcs_impl.py, torch_np/_ndarray.py, torch_np/_reductions.py, torch_np/_ufuncs.py, torch_np/_util.py, torch_np/linalg.py
Make result_type inference use tensors internally. This simplifies internal usage a bit, and serves as a prerequisite for introducing weak scalars, cf gh-137 (off which this PR is split).
=> MAINT: rework result_type_impl to accept *tensors, not dtypes

torch_np/tests/test_dtype.py, torch_np/tests/test_xps.py
Starts from https://github.com/Quansight-Labs/numpy_pytorch_interop/pull/116 as that contains a few useful tidbits.
@ev-br see `test_dtype.py` for the failing tests I wrote for converting NumPy dtypes (and thus arrays) to the equivalent interop dtypes. Currently its a mixed bag on what gets converted correctly
```
'bool'                    PASSED
np.dtype('bool')          FAILED
'bool_'                   FAILED
np.bool_                  FAILED
np.dtype('bool_')         FAILED
'int8'                    PASSED
np.int8                   FAILED
np.dtype('int8')          PASSED
'int16'                   PASSED
np.int16                  FAILED
np.dtype('int16')         PASSED
'int32'                   PASSED
np.int32                  FAILED
np.dtype('int32')         PASSED
'int64' …
```
=> Tests for converting NumPy dtypes to their equivalent

torch_np/_ndarray.py, torch_np/_util.py, torch_np/tests/test_basic.py
Needed for arrays hiding as elements of nested lists e.g. `np.array([[1, 2], [3, np.array(4)]])`.
Split off from gh-137.
=> BUG: make array-detection logic in array(...) more robust

torch_np/_dtypes_impl.py, torch_np/_ufuncs.py, torch_np/tests/test_nep50_examples.py, torch_np/tests/test_ufuncs_basic.py
Note that this PR is against the branch from https://github.com/Quansight-Labs/numpy_pytorch_interop/pull/140.
This PR tries to solve in a clean way some simpler cases first (dtype is not None, or we have two tensors) to be able to deal with the tricky part having some preconditions on the data. This fixes a couple bugs that were latent in the other branch. It also adds a test to test for this case.
The logic to solve NEP 50 is still that of https://github.com/Quansight-Labs/numpy_pytorch_interop/pull/140 for the tricky case.
It also tries to avoid iterations over lists that can be very slow. See if the timings of CI agree with this.
=> ENH: NEP 50 "weak scalars" with dtype and PyTorch defaults

torch_np/_ndarray.py, torch_np/tests/numpy_tests/core/test_indexing.py, torch_np/tests/numpy_tests/core/test_multiarray.py
The main change here is to allow a list (here, `[2, 3, 4]`) in the right-hand side of 
```     
a = np.zeros((5, 5))
a[[[0], [1], [2]], [0, 1, 2]] = [2, 3, 4]
```
=> pick some low-hanging fruit in advanced indexing

.gitignore, autogen/numpy_api_dump.py, torch_np/_funcs_impl.py, torch_np/tests/numpy_tests/lib/test_arraypad.py
Only `mode="constant"` for now, and only scalar fill_values. Broadcasted fill_values do not seem to be supported by `torch.nn.functional.pad`, which this function delegates to.
=> implement np.pad

autogen/numpy_api_dump.py, torch_np/_funcs_impl.py, torch_np/tests/test_function_base.py
Vendor the numpy source; take docstring examples into tests.
=> ENH: add np.append

torch_np/_funcs_impl.py, torch_np/_reductions.py, torch_np/tests/numpy_tests/core/test_multiarray.py, torch_np/tests/numpy_tests/lib/test_function_base.py, torch_np/tests/numpy_tests/lib/test_twodim_base.py, torch_np/tests/numpy_tests/lib/test_type_check.py, torch_np/tests/test_nep50_examples.py, torch_np/tests/test_ufuncs_basic.py
- Comb through xfails, remove several unneeded ones or fix small errors which these xfails were masking.
- Update the NEP50 test for the NEP update.
=> fix dtype edge cases in var, std, dot; remove (some) expired xfails

torch_np/_dtypes.py
as discussed over at https://github.com/pytorch/pytorch/pull/103546
With this, both dtype and array scalars are regular classes/objects:
```
In [6]: tnp.float32.__mro__
Out[6]: 
(torch_np._dtypes.float32,
torch_np._dtypes.floating,
torch_np._dtypes.inexact,
torch_np._dtypes.number,
torch_np._dtypes.generic,
object)
In [7]: tnp.dtype(int).__class__.__mro__
Out[7]: (torch_np._dtypes.DType, object)
```
cc @lezcano @larryliu0820
=> MAINT: remove abc.ABC from dtype hierarchy

torch_np/_binary_ufuncs_impl.py, torch_np/_ufuncs.py, torch_np/_util.py, torch_np/tests/test_nep50_examples.py, torch_np/tests/test_ufuncs_basic.py
the second commit is just trivial MAINT while I'm looking at this file
=> fix ldexp casting + unary ufunc dtypes
